dsn0: &dsn0
  "root:ag0HRV&NF8a7IdHS@(10.0.3.203:3306)/hezi?charset=utf8&parseTime=True&loc=Local"
dsn1: &dsn1
  "root:ag0HRV&NF8a7IdHS@(10.0.3.203:3306)/log?charset=utf8&parseTime=True&loc=Local"
startConditionVal: &startConditionVal
  - 1
startCondition: &startCondition
  {"id >= ?":*startConditionVal}
task:
    - {"dsn0":*dsn0,"t0":"user","dsnType0":"mysql","dsn1":*dsn1,"t1":"user_bak","dsnType1":"mysql",
       "startFuncType":1,"startCondition": *startCondition,"nextFuncType":2,"nextKey":"id","created":true}
